version: "3.9"

services:
  backend:
    build: ./blog-backend
    container_name: blog-backend
    environment:
      ARTICLES_PATH: /app/articles
      BLOG_CORS_ALLOWED_ORIGINS: http://localhost
    volumes:
      - ./articles:/app/articles
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./blog-frontend
    container_name: blog-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always
